App::Application.routes.draw do
  get "/"                          => "main#root"                       ,as: "root"
  get "/pic_category"              => "main#pic_category"               ,as: "pic_category" 
  get "/contact"                   => "main#contact"                    ,as: "contact"
  get "/comment_blog"              => "main#comment_blog"               ,as: "comment_blog"
  get "/alaska"                    => "main#alaska"                     ,as: "alaska"
  get "/albq_balloon"              => "main#albq_balloon"               ,as: "albq_balloon"
  get "/colorado"                  => "main#colorado"                   ,as: "colorado"
  get "/fall_colors"               => "main#fall_colors"                ,as: "fall_colors"
  get "/test_pictures"             => "main#test_pictures"              ,as: "test_pictures"
  get "/wild_flowers"              => "main#wild_flowers"               ,as: "wild_flowers"
  get "/select_national_parks"     => "main#select_national_parks"      ,as: "select_national_parks"
  get "/rocky_mtn_np"              => "main#rocky_mtn_np"               ,as: "rocky_mtn_np"
  get "/arches_np"                 => "main#arches_np"                  ,as: "arches_np"
  get "/bryce_canyon_np"           => "main#bryce_canyon_np"            ,as: "bryce_canyon_np"
  get "/index"                     => "main#index"                      ,as: "index"
  get "/special_occassions"        => "main#special_occassions"         ,as: "special_occassions"
  get "/admin_login"               => "main#admin_login"                ,as: "admin_login"
  get "/admin"                     => "main#admin"                      ,as: "admin"
  get "/so_login"                  => "main#so_login"                   ,as: "so_login"
  post "/so_login_post"            => "main#so_login_post"              ,as: "so_login_post"
  post "/admin_login_post"         => "main#admin_login_post"           ,as: "admin_login_post"
end
