NationalPark.create! image1: "saguaro01.jpg",      image2: "saguaro02.jpg",      name: "saguaro",        description: "The Cactus OF Saguaro National Park"                
NationalPark.create! image1: "saguaro03.jpg",      image2: "saguaro04.jpg",      name: "saguaro",        description: "Saguaro National Park" 
NationalPark.create! image1: "saguaro05.jpg",      image2: "saguaro06.jpg",      name: "saguaro",        description: "Saguaro & Prickley Pear Cactus"     
NationalPark.create! image1: "saguaro07.jpg",      image2: "saguaro08.jpg",      name: "saguaro",        description: "A Lot Of Saguaro Cactus"            
NationalPark.create! image1: "saguaro09.jpg",      image2: "saguaro10.jpg",      name: "saguaro",        description: "Saguaros Cactus"           
NationalPark.create! image1: "saguaro11.jpg",      image2: "saguaro12.jpg",      name: "saguaro",        description: "Check Out The Sky"           
NationalPark.create! image1: "saguaro13.jpg",      image2: "saguaro14.jpg",      name: "saguaro",        description: "Saguaros Cactus"           
NationalPark.create! image1: "saguaro15.jpg",      image2: "saguaro16.jpg",      name: "saguaro",        description: "Saguaro & Prickley Pear Cactus"             
NationalPark.create! image1: "saguaro17.jpg",      image2: "saguaro18.jpg",      name: "saguaro",        description: "Saguaros Cactus"             
NationalPark.create! image1: "saguaro19.jpg",      image2: "saguaro20.jpg",      name: "saguaro",        description: "Prickley Pear Cactus"  
NationalPark.create! image1: "saguaro21.jpg",      image2: "saguaro22.jpg",      name: "saguaro",        description: "Prickley Pear Cactus"        
NationalPark.create! image1: "saguaro23.jpg",      image2: "saguaro24.jpg",      name: "saguaro",        description: "More Saguaro Cactus"            
NationalPark.create! image1: "saguaro25.jpg",      image2: "saguaro26.jpg",      name: "saguaro",        description: "A Single Saguaro Cacti"                   
NationalPark.create! image1: "saguaro27.jpg",      image2: "saguaro28.jpg",      name: "saguaro",        description: "Saguaro & Prickley Pear Cactus"     
NationalPark.create! image1: "saguaro29.jpg",      image2: "saguaro30.jpg",      name: "saguaro",        description: "Prickley Pear & Jumping Cholla"                      
NationalPark.create! image1: "saguaro31.jpg",      image2: "saguaro32.jpg",      name: "saguaro",        description: "A Saguaro With Multiple Arms"
NationalPark.create! image1: "saguaro33.jpg",      image2: "saguaro34.jpg",      name: "saguaro",        description: "A Saguaro & Jumping Cholla"            
NationalPark.create! image1: "saguaro35.jpg",      image2: "saguaro36.jpg",      name: "saguaro",        description: "Prickley Pear Cactus"                   
NationalPark.create! image1: "saguaro37.jpg",      image2: "saguaro38.jpg",      name: "saguaro",        description: "A Saguaro & Jumping Cholla"     
NationalPark.create! image1: "saguaro39.jpg",      image2: "saguaro40.jpg",      name: "saguaro",        description: "Jumping Cholla Cactus"                      
NationalPark.create! image1: "saguaro41.jpg",      image2: "saguaro42.jpg",      name: "saguaro",        description: "A Saguaro With A Lot Arms"
NationalPark.create! image1: "saguaro43.jpg",      image2: "saguaro44.jpg",      name: "saguaro",        description: "Jumping Cholla & A Saguaro"
NationalPark.create! image1: "saguaro45.jpg",      image2: "saguaro46.jpg",      name: "saguaro",        description: "A Saguaro With Mountain View"
NationalPark.create! image1: "saguaro47.jpg",      image2: "saguaro48.jpg",      name: "saguaro",        description: "A Lot Of Prickley Pear Cactus"
Title.create! name: "saguaro",          description: "SAGUARO NATIONAL PARK: is located in southern Arizona.  The park has two districts embracing Tucson from the East and West.  The Rincon Mountain District is East of Tucson and the Tucson Mountain District is West of Tucson.  The total area is 91,442 acres of which 70,905 acres is designate wilderness.  There is a visitor center in each of the two districts.  Both districts conserve fine tracts of the Sonoran Desert, including ranges of significant hills, the Tucson Mountains in the west and the Rincon Mountains in the east.  The park gets its name from the saguaro, a large cactus which is native to the region. Many other kinds of cactus, including barrel, cholla, and prickly pear are abundant in the park.  Saguaro National Monument was created on March 1, 1933 by President Herbert Hoover.  On October 14, 1994, Congress elevated Saguaro to National Park status."

