Admin.create! user_name: "DRMowrer", password: "08MyLife26!"
EventCode.create! event_code: "mowrer08172003"
EventCode.create! event_code: "karrie10272007"
EventCode.create! event_code: "noga09272005"
EventCode.create! event_code: "admin"
Location.create! name: "Alaska"
Location.create! name: "Albuquerque Balloons"
Location.create! name: "Arches NP"
Location.create! name: "Bent Fort National Historical Site"
Location.create! name: "Black Canyon NP"
Location.create! name: "Bryce Canyon NP"
Location.create! name: "Colorado"
Location.create! name: "Denali NP"
Location.create! name: "Everglades NP"
Location.create! name: "Fall Colors"
Location.create! name: "Florida"
Location.create! name: "Grand Canyon NP"
Location.create! name: "Hawaii"
Location.create! name: "Hawaii Volcanoes NP"
Location.create! name: "Independence National Historical Park"
Location.create! name: "Jacksonville Air Show"
Location.create! name: "Kenai Fjords NP"
Location.create! name: "Mesa Verde NP"
Location.create! name: "Other"
Location.create! name: "Rocky Mountain NP"
Location.create! name: "Special Occasions"
Location.create! name: "Valley Forge NP"
Location.create! name: "Yellowstone NP"
Picture.create! image1: "albq_balloon01.jpg", image2: "albq_balloon02.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon03.jpg", image2: "albq_balloon04.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon05.jpg", image2: "albq_balloon06.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon07.jpg", image2: "albq_balloon08.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon09.jpg", image2: "albq_balloon10.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon11.jpg", image2: "albq_balloon12.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon13.jpg", image2: "albq_balloon14.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon15.jpg", image2: "albq_balloon16.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon17.jpg", image2: "albq_balloon18.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon19.jpg", image2: "albq_balloon20.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon21.jpg", image2: "albq_balloon22.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon23.jpg", image2: "albq_balloon24.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon25.jpg", image2: "albq_balloon26.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon27.jpg", image2: "albq_balloon28.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon29.jpg", image2: "albq_balloon30.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon31.jpg", image2: "albq_balloon32.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon33.jpg", image2: "albq_balloon34.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon35.jpg", image2: "albq_balloon36.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon37.jpg", image2: "albq_balloon38.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon39.jpg", image2: "albq_balloon40.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon41.jpg", image2: "albq_balloon42.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon43.jpg", image2: "albq_balloon44.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon45.jpg", image2: "albq_balloon46.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005" 
Picture.create! image1: "albq_balloon47.jpg", image2: "albq_balloon48.jpg", category: "albq_balloon", description: "Balloon Fiesta 2005"
Picture.create! image1: "fall_colors01.jpg",  image2: "fall_colors02.jpg",  category: "fall_colors",  description: "Boreas Pass, CO"      
Picture.create! image1: "fall_colors03.jpg",  image2: "fall_colors04.jpg",  category: "fall_colors",  description: "Kenosha Pass, CO"     
Picture.create! image1: "fall_colors05.jpg",  image2: "fall_colors06.jpg",  category: "fall_colors",  description: "Telluride, CO"        
Picture.create! image1: "fall_colors07.jpg",  image2: "fall_colors08.jpg",  category: "fall_colors",  description: "Kebler Pass, CO"       
Picture.create! image1: "fall_colors09.jpg",  image2: "fall_colors10.jpg",  category: "fall_colors",  description: "Kenosha Pass, CO"     
Picture.create! image1: "fall_colors11.jpg",  image2: "fall_colors12.jpg",  category: "fall_colors",  description: "Ouray, CO"            
Picture.create! image1: "fall_colors13.jpg",  image2: "fall_colors14.jpg",  category: "fall_colors",  description: "Boreas Pass, CO"      
Picture.create! image1: "fall_colors15.jpg",  image2: "fall_colors16.jpg",  category: "fall_colors",  description: "Coal Bank Pass, CO"   
Picture.create! image1: "fall_colors17.jpg",  image2: "fall_colors18.jpg",  category: "fall_colors",  description: "Purgatory, CO"        
Picture.create! image1: "fall_colors19.jpg",  image2: "fall_colors20.jpg",  category: "fall_colors",  description: "Kebler Pass, CO"       
Picture.create! image1: "fall_colors21.jpg",  image2: "fall_colors22.jpg",  category: "fall_colors",  description: "Indepenence Pass, CO" 
Picture.create! image1: "fall_colors23.jpg",  image2: "fall_colors24.jpg",  category: "fall_colors",  description: "Crystal River, CO"    
Picture.create! image1: "fall_colors25.jpg",  image2: "fall_colors26.jpg",  category: "fall_colors",  description: "Maroons Bells Aspen"        
Picture.create! image1: "fall_colors27.jpg",  image2: "fall_colors28.jpg",  category: "fall_colors",  description: "Maroons Bells Aspen"
Picture.create! image1: "fall_colors29.jpg",  image2: "fall_colors30.jpg",  category: "fall_colors",  description: "Hwy 72 CO"        
Picture.create! image1: "fall_colors31.jpg",  image2: "fall_colors32.jpg",  category: "fall_colors",  description: "Lizard Head Pass, CO" 
Picture.create! image1: "wild_flowers01.jpg", image2: "wild_flowers02.jpg", category: "wild_flowers", description: "Shrine Pass, CO"      
Picture.create! image1: "wild_flowers03.jpg", image2: "wild_flowers04.jpg", category: "wild_flowers", description: "Red Cliff, CO"        
Picture.create! image1: "wild_flowers05.jpg", image2: "wild_flowers06.jpg", category: "wild_flowers", description: "Crested Butte, CO"    
Picture.create! image1: "wild_flowers07.jpg", image2: "wild_flowers08.jpg", category: "wild_flowers", description: "Crested Butte, CO"     
Picture.create! image1: "wild_flowers09.jpg", image2: "wild_flowers10.jpg", category: "wild_flowers", description: "Crested Butte, CO"    
Picture.create! image1: "wild_flowers11.jpg", image2: "wild_flowers12.jpg", category: "wild_flowers", description: "Crested Butte, CO"    
Picture.create! image1: "wild_flowers13.jpg", image2: "wild_flowers14.jpg", category: "wild_flowers", description: "Shrine Pass, CO"
Picture.create! image1: "wild_flowers15.jpg", image2: "wild_flowers16.jpg", category: "wild_flowers", description: "Shrine Pass, CO"      
Picture.create! image1: "wild_flowers17.jpg", image2: "wild_flowers18.jpg", category: "wild_flowers", description: "Shrine Pass, CO"      
Picture.create! image1: "wild_flowers19.jpg", image2: "wild_flowers20.jpg", category: "wild_flowers", description: "Crested Butte, CO"     
Picture.create! image1: "wild_flowers21.jpg", image2: "wild_flowers22.jpg", category: "wild_flowers", description: "Shrine Pass, CO"      
Picture.create! image1: "wild_flowers23.jpg", image2: "wild_flowers24.jpg", category: "wild_flowers", description: "Crested Butte, CO"    
Picture.create! image1: "wild_flowers25.jpg", image2: "wild_flowers26.jpg", category: "wild_flowers", description: "Rocky Mtn National Park" 
Picture.create! image1: "wild_flowers27.jpg", image2: "wild_flowers28.jpg", category: "wild_flowers", description: "Rocky Mtn National Park" 
Picture.create! image1: "wild_flowers29.jpg", image2: "wild_flowers30.jpg", category: "wild_flowers", description: "Rocky Mtn National Park" 
Picture.create! image1: "wild_flowers31.jpg", image2: "wild_flowers32.jpg", category: "wild_flowers", description: "Rocky Mtn National Park" 
Picture.create! image1: "colorado01.jpg",     image2: "colorado02.jpg",     category: "colorado",     description: "Coors Field Sunset"                 
Picture.create! image1: "colorado03.jpg",     image2: "colorado04.jpg",     category: "colorado",     description: "Hwy 7 St Milo"               
Picture.create! image1: "colorado05.jpg",     image2: "colorado06.jpg",     category: "colorado",     description: "Brook Trout St. Vrain River" 
Picture.create! image1: "colorado07.jpg",     image2: "colorado08.jpg",     category: "colorado",     description: "Indian Peaks Wilderness"     
Picture.create! image1: "colorado09.jpg",     image2: "colorado10.jpg",     category: "colorado",     description: "Hwy 7 Meeker Park"           
Picture.create! image1: "colorado11.jpg",     image2: "colorado12.jpg",     category: "colorado",     description: "Brainard Lake Area"          
Picture.create! image1: "colorado13.jpg",     image2: "colorado14.jpg",     category: "colorado",     description: "Mt Stream Shrine Pass"       
Picture.create! image1: "colorado15.jpg",     image2: "colorado16.jpg",     category: "colorado",     description: "Sunset Golden Ponds Longmont"       
Picture.create! image1: "colorado17.jpg",     image2: "colorado18.jpg",     category: "colorado",     description: "Snowy Golden Ponds Longmont"       
Picture.create! image1: "colorado19.jpg",     image2: "colorado20.jpg",     category: "colorado",     description: "Are they really golfers?"    
Picture.create! image1: "colorado21.jpg",     image2: "colorado22.jpg",     category: "colorado",     description: "Creaste Butte"               
Picture.create! image1: "colorado23.jpg",     image2: "colorado24.jpg",     category: "colorado",     description: "Hwy 7 Meeker Park"
Picture.create! image1: "colorado25.jpg",     image2: "colorado26.jpg",     category: "colorado",     description: "Mountain Stream Aspen"
Picture.create! image1: "colorado27.jpg",     image2: "colorado28.jpg",     category: "colorado",     description: "Maroon Bells Aspen" 
Picture.create! image1: "colorado29.jpg",     image2: "colorado30.jpg",     category: "colorado",     description: "Sunset Golden Ponds"        
Picture.create! image1: "colorado31.jpg",     image2: "colorado32.jpg",     category: "colorado",     description: "St Milo Fall Colors"
Picture.create! image1: "colorado33.jpg",     image2: "colorado34.jpg",     category: "colorado",     description: "Coyote Running"                 
Picture.create! image1: "colorado35.jpg",     image2: "colorado36.jpg",     category: "colorado",     description: "Sunset"               
Picture.create! image1: "colorado37.jpg",     image2: "colorado38.jpg",     category: "colorado",     description: "Sunrise" 
Picture.create! image1: "colorado39.jpg",     image2: "colorado40.jpg",     category: "colorado",     description: "Twin Lakes"     
Picture.create! image1: "colorado41.jpg",     image2: "colorado42.jpg",     category: "colorado",     description: "Gloden Ponds Reflections"           
Picture.create! image1: "colorado43.jpg",     image2: "colorado44.jpg",     category: "colorado",     description: "Mountains Creaste Butte"          
Picture.create! image1: "colorado45.jpg",     image2: "colorado46.jpg",     category: "colorado",     description: "Jessica & Buddy Lazier Indy Car"       
Picture.create! image1: "colorado47.jpg",     image2: "colorado48.jpg",     category: "colorado",     description: "Mounatains"       
Picture.create! image1: "colorado49.jpg",     image2: "colorado50.jpg",     category: "colorado",     description: "Ralphie - CU Mascot"       
Picture.create! image1: "colorado51.jpg",     image2: "colorado52.jpg",     category: "colorado",     description: "Golden Ponds"    
Picture.create! image1: "colorado53.jpg",     image2: "colorado54.jpg",     category: "colorado",     description: "Brainard Lake"               
Picture.create! image1: "colorado55.jpg",     image2: "colorado56.jpg",     category: "colorado",     description: "Old Mounatain Mining Town"
Picture.create! image1: "colorado57.jpg",     image2: "colorado58.jpg",     category: "colorado",     description: "Roosevelt Park - Longmont"
Picture.create! image1: "colorado59.jpg",     image2: "colorado60.jpg",     category: "colorado",     description: "Westcliff" 
Picture.create! image1: "colorado61.jpg",     image2: "colorado62.jpg",     category: "colorado",     description: "La Junta"        
Picture.create! image1: "colorado63.jpg",     image2: "colorado64.jpg",     category: "colorado",     description: "Golden Ponds" 
Picture.create! image1: "colorado65.jpg",     image2: "colorado66.jpg",     category: "colorado",     description: "Mountain Stream Shrine Pass"       
Picture.create! image1: "colorado67.jpg",     image2: "colorado68.jpg",     category: "colorado",     description: "Deer Creaste Butte"       
Picture.create! image1: "colorado69.jpg",     image2: "colorado70.jpg",     category: "colorado",     description: "Rockies Game"       
Picture.create! image1: "colorado71.jpg",     image2: "colorado72.jpg",     category: "colorado",     description: "Sunset In The Mountains"    
Picture.create! image1: "colorado73.jpg",     image2: "colorado74.jpg",     category: "colorado",     description: "Mountain Waterfall"               
Picture.create! image1: "colorado75.jpg",     image2: "colorado76.jpg",     category: "colorado",     description: "Boulder Falls"
Picture.create! image1: "colorado77.jpg",     image2: "colorado78.jpg",     category: "colorado",     description: "Westcliff - Wet Mountains"
Picture.create! image1: "colorado79.jpg",     image2: "colorado80.jpg",     category: "colorado",     description: "Golden Ponds"             
Picture.create! image1: "alaska01.jpg",       image2: "alaska02.jpg",       category: "alaska",       description: "Johnson Creek"                 
Picture.create! image1: "alaska03.jpg",       image2: "alaska04.jpg",       category: "alaska",       description: "Maggie's Silver Johnson Creek" 
Picture.create! image1: "alaska05.jpg",       image2: "alaska06.jpg",       category: "alaska",       description: "Bear Print"                    
Picture.create! image1: "alaska07.jpg",       image2: "alaska08.jpg",       category: "alaska",       description: "Bear Tracks On River Bank"     
Picture.create! image1: "alaska09.jpg",       image2: "alaska10.jpg",       category: "alaska",       description: "Otter Creek Big Silver"  
Picture.create! image1: "alaska11.jpg",       image2: "alaska12.jpg",       category: "alaska",       description: "Anchorage"                     
Picture.create! image1: "alaska13.jpg",       image2: "alaska14.jpg",       category: "alaska",       description: "Alaska Range Mts"              
Picture.create! image1: "alaska15.jpg",       image2: "alaska16.jpg",       category: "alaska",       description: "Otter Creek Alaska Range Mts"
Picture.create! image1: "alaska17.jpg",       image2: "alaska18.jpg",       category: "alaska",       description: "Alaskan Rail Road"                 
Picture.create! image1: "alaska19.jpg",       image2: "alaska20.jpg",       category: "alaska",       description: "How Many Salmon Can You Count?" 
Picture.create! image1: "alaska21.jpg",       image2: "alaska22.jpg",       category: "alaska",       description: "Good Bear Protection"                    
Picture.create! image1: "alaska23.jpg",       image2: "alaska24.jpg",       category: "alaska",       description: "Alaskan Walkway"     
Picture.create! image1: "alaska25.jpg",       image2: "alaska26.jpg",       category: "alaska",       description: "Reflections"  
Picture.create! image1: "alaska27.jpg",       image2: "alaska28.jpg",       category: "alaska",       description: "Early Morning Fog"                     
Picture.create! image1: "alaska29.jpg",       image2: "alaska30.jpg",       category: "alaska",       description: "Reflections"              
Picture.create! image1: "alaska31.jpg",       image2: "alaska32.jpg",       category: "alaska",       description: "Bald Eagles" 
Picture.create! image1: "florida01.jpg", image2: "florida02.jpg", category: "florida", description: "Catching A Wave" 
Picture.create! image1: "florida03.jpg", image2: "florida04.jpg", category: "florida", description: "Jacksonville Beach" 
Picture.create! image1: "florida05.jpg", image2: "florida06.jpg", category: "florida", description: "Jacksonville St. Jonhs River" 
Picture.create! image1: "florida07.jpg", image2: "florida08.jpg", category: "florida", description: "Albino Alligator" 
Picture.create! image1: "florida09.jpg", image2: "florida10.jpg", category: "florida", description: "Sand Castle South Beach" 
Picture.create! image1: "florida11.jpg", image2: "florida12.jpg", category: "florida", description: "I Think I Can See Cuba" 
Picture.create! image1: "florida13.jpg", image2: "florida14.jpg", category: "florida", description: "Lizards Climb Everywhere" 
Picture.create! image1: "florida15.jpg", image2: "florida16.jpg", category: "florida", description: "That's How To Fish In Florida" 
Picture.create! image1: "florida17.jpg", image2: "florida18.jpg", category: "florida", description: "Beach North Of Jacksonville" 
Picture.create! image1: "florida19.jpg", image2: "florida20.jpg", category: "florida", description: "Light House St. Augustine" 
Picture.create! image1: "florida21.jpg", image2: "florida22.jpg", category: "florida", description: "Spanish Moss" 
Picture.create! image1: "florida23.jpg", image2: "florida24.jpg", category: "florida", description: "Art Deco South Beach" 
Picture.create! image1: "florida25.jpg", image2: "florida26.jpg", category: "florida", description: "Jacksonville Landing" 
Picture.create! image1: "florida27.jpg", image2: "florida28.jpg", category: "florida", description: "Sunrise In Key West" 
Picture.create! image1: "florida29.jpg", image2: "florida30.jpg", category: "florida", description: "Say No More Margartaville Key West" 
Picture.create! image1: "florida31.jpg", image2: "florida32.jpg", category: "florida", description: "Sunset Key West" 
Picture.create! image1: "florida33.jpg", image2: "florida34.jpg", category: "florida", description: "End Of Hwy 1 key West" 
Picture.create! image1: "florida35.jpg", image2: "florida36.jpg", category: "florida", description: "Begining Of Hwy 1 Key West" 
Picture.create! image1: "florida37.jpg", image2: "florida38.jpg", category: "florida", description: "Now That's A Lawn Ornament" 
Picture.create! image1: "florida39.jpg", image2: "florida40.jpg", category: "florida", description: "They Come In All Colors In Florida" 
Picture.create! image1: "florida41.jpg", image2: "florida42.jpg", category: "florida", description: "The Pirates Invade Jacksonville" 
Picture.create! image1: "florida43.jpg", image2: "florida44.jpg", category: "florida", description: "Raise The Road For The Big Boats" 
Picture.create! image1: "florida45.jpg", image2: "florida46.jpg", category: "florida", description: "The Jacksonville Jaguars Stadium" 
Picture.create! image1: "florida47.jpg", image2: "florida48.jpg", category: "florida", description: "Key West"
Picture.create! image1: "swooping01.jpg", image2: "swooping02.jpg", category: "swooping", description: "Here We Go" 
Picture.create! image1: "swooping03.jpg", image2: "swooping04.jpg", category: "swooping", description: "Wheres My Skis" 
Picture.create! image1: "swooping05.jpg", image2: "swooping06.jpg", category: "swooping", description: "A Little To Close" 
Picture.create! image1: "swooping07.jpg", image2: "swooping08.jpg", category: "swooping", description: "A Right Turn" 
Picture.create! image1: "swooping09.jpg", image2: "swooping10.jpg", category: "swooping", description: "Splash" 
Picture.create! image1: "swooping11.jpg", image2: "swooping12.jpg", category: "swooping", description: "Grils Can Play Too" 
Picture.create! image1: "swooping13.jpg", image2: "swooping14.jpg", category: "swooping", description: "Almost Made It" 
Picture.create! image1: "swooping15.jpg", image2: "swooping16.jpg", category: "swooping", description: "Setting Up For A Swoop" 
Picture.create! image1: "swooping17.jpg", image2: "swooping18.jpg", category: "swooping", description: "Better Luck Next Time" 
Picture.create! image1: "swooping19.jpg", image2: "swooping20.jpg", category: "swooping", description: "A Walk In The Water" 
Picture.create! image1: "swooping21.jpg", image2: "swooping22.jpg", category: "swooping", description: "All Wet" 
Picture.create! image1: "swooping23.jpg", image2: "swooping24.jpg", category: "swooping", description: "A Little Sideways" 
Picture.create! image1: "swooping25.jpg", image2: "swooping26.jpg", category: "swooping", description: "Safe" 
Picture.create! image1: "swooping27.jpg", image2: "swooping28.jpg", category: "swooping", description: "Laying On The Water" 
Picture.create! image1: "swooping29.jpg", image2: "swooping30.jpg", category: "swooping", description: "I Will Sit Here Here" 
Picture.create! image1: "swooping31.jpg", image2: "swooping32.jpg", category: "swooping", description: "A BIG Splash" 
Picture.create! image1: "swooping33.jpg", image2: "swooping34.jpg", category: "swooping", description: "I've Got This" 
Picture.create! image1: "swooping35.jpg", image2: "swooping36.jpg", category: "swooping", description: "I am Still Upright" 
Picture.create! image1: "swooping37.jpg", image2: "swooping38.jpg", category: "swooping", description: "I am Going To Get Wet" 
Picture.create! image1: "swooping39.jpg", image2: "swooping40.jpg", category: "swooping", description: "I Made It" 
Picture.create! image1: "swooping41.jpg", image2: "swooping42.jpg", category: "swooping", description: "That Will Leave A Mark" 
Picture.create! image1: "swooping43.jpg", image2: "swooping44.jpg", category: "swooping", description: "Photographer Beware" 
Picture.create! image1: "swooping45.jpg", image2: "swooping46.jpg", category: "swooping", description: "Look Mom One Leg" 
Picture.create! image1: "swooping47.jpg", image2: "swooping48.jpg", category: "swooping", description: "Will I Make It" 
Picture.create! image1: "jax01.jpg",          image2: "jax02.jpg",          category: "jax_air_show", description: "Blue Angles" 
Picture.create! image1: "jax03.jpg",          image2: "jax04.jpg",          category: "jax_air_show", description: "Blue Angles Who's Upside Down?"
Picture.create! image1: "jax05.jpg",          image2: "jax06.jpg",          category: "jax_air_show", description: "Blue Angles" 
Picture.create! image1: "jax07.jpg",          image2: "jax08.jpg",          category: "jax_air_show", description: "Blue Angles"
Picture.create! image1: "jax09.jpg",          image2: "jax10.jpg",          category: "jax_air_show", description: "Blue Angle" 
Picture.create! image1: "jax11.jpg",          image2: "jax12.jpg",          category: "jax_air_show", description: "Blue Angles"
Picture.create! image1: "jax13.jpg",          image2: "jax14.jpg",          category: "jax_air_show", description: "Blue Angles" 
Picture.create! image1: "jax15.jpg",          image2: "jax16.jpg",          category: "jax_air_show", description: "Army Bi-Plane In The Smoke"
Picture.create! image1: "jax17.jpg",          image2: "jax18.jpg",          category: "jax_air_show", description: "Bi-Plane In The Smoke"
Picture.create! image1: "jax19.jpg",          image2: "jax20.jpg",          category: "jax_air_show", description: "Bi-Plane In The Smoke" 
Picture.create! image1: "jax21.jpg",          image2: "jax22.jpg",          category: "jax_air_show", description: "Bi-Plane In The Smoke"
Picture.create! image1: "jax23.jpg",          image2: "jax24.jpg",          category: "jax_air_show", description: "Blue Angles"
Picture.create! image1: "jax25.jpg",          image2: "jax26.jpg",          category: "jax_air_show", description: "Bi-Plane"
Picture.create! image1: "jax27.jpg",          image2: "jax28.jpg",          category: "jax_air_show", description: "Bi-Plane" 
Picture.create! image1: "jax29.jpg",          image2: "jax30.jpg",          category: "jax_air_show", description: "Napalm Drop Feel The Heat"
Picture.create! image1: "jax31.jpg",          image2: "jax32.jpg",          category: "jax_air_show", description: "Jacksonville Blue Angles"
NationalPark.create! image1: "arches01.jpg",    image2: "arches02.jpg",    name: "arches",         description: "Arches NP"      
NationalPark.create! image1: "arches03.jpg",    image2: "arches04.jpg",    name: "arches",         description: "Two Bird Arch"       
NationalPark.create! image1: "arches05.jpg",    image2: "arches06.jpg",    name: "arches",         description: "Three Kings"         
NationalPark.create! image1: "arches07.jpg",    image2: "arches08.jpg",    name: "arches",         description: "Arches NP"      
NationalPark.create! image1: "arches09.jpg",    image2: "arches10.jpg",    name: "arches",         description: "Arches NP"           
NationalPark.create! image1: "arches11.jpg",    image2: "arches12.jpg",    name: "arches",         description: "Balance Rock"        
NationalPark.create! image1: "arches13.jpg",    image2: "arches14.jpg",    name: "arches",         description: "Arches NP"           
NationalPark.create! image1: "arches15.jpg",    image2: "arches16.jpg",    name: "arches",         description: "Arches NP" 
NationalPark.create! image1: "arches17.jpg",    image2: "arches18.jpg",    name: "arches",         description: "Arches NP"        
NationalPark.create! image1: "arches19.jpg",    image2: "arches20.jpg",    name: "arches",         description: "Arches NP"
NationalPark.create! image1: "arches21.jpg",    image2: "arches22.jpg",    name: "arches",         description: "Double Arches"        
NationalPark.create! image1: "arches23.jpg",    image2: "arches24.jpg",    name: "arches",         description: "Arches NP"           
NationalPark.create! image1: "arches25.jpg",    image2: "arches26.jpg",    name: "arches",         description: "Arches NP" 
NationalPark.create! image1: "arches27.jpg",    image2: "arches28.jpg",    name: "arches",         description: "Arches NP"           
NationalPark.create! image1: "arches29.jpg",    image2: "arches30.jpg",    name: "arches",         description: "Three Wise Men" 
NationalPark.create! image1: "arches31.jpg",    image2: "arches32.jpg",    name: "arches",         description: "The Monkeys"           
NationalPark.create! image1: "bryce_np01.jpg",  image2: "bryce_np02.jpg",  name: "bryce_canyon",   description: "Sunrise Point"           
NationalPark.create! image1: "bryce_np03.jpg",  image2: "bryce_np04.jpg",  name: "bryce_canyon",   description: "Landscape"         
NationalPark.create! image1: "bryce_np05.jpg",  image2: "bryce_np06.jpg",  name: "bryce_canyon",   description: "Sunset Point"            
NationalPark.create! image1: "bryce_np07.jpg",  image2: "bryce_np08.jpg",  name: "bryce_canyon",   description: "Sunrise Point" 
NationalPark.create! image1: "bryce_np09.jpg",  image2: "bryce_np10.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np11.jpg",  image2: "bryce_np12.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np13.jpg",  image2: "bryce_np14.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np15.jpg",  image2: "bryce_np16.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np17.jpg",  image2: "bryce_np18.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np19.jpg",  image2: "bryce_np20.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np21.jpg",  image2: "bryce_np22.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np23.jpg",  image2: "bryce_np24.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np25.jpg",  image2: "bryce_np26.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np27.jpg",  image2: "bryce_np28.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np29.jpg",  image2: "bryce_np30.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP"     
NationalPark.create! image1: "bryce_np31.jpg",  image2: "bryce_np32.jpg",  name: "bryce_canyon",   description: "Bryce Canyon NP" 
NationalPark.create! image1: "denali01.jpg",    image2: "denali02.jpg",    name: "denali",     description: "Mount McKinley 20,237 Feet Above Sea Level"
NationalPark.create! image1: "denali03.jpg",    image2: "denali04.jpg",    name: "denali",     description: "Caribou Grazing"
NationalPark.create! image1: "denali05.jpg",    image2: "denali06.jpg",    name: "denali",     description: "Dall Sheep Grazing"
NationalPark.create! image1: "denali07.jpg",    image2: "denali08.jpg",    name: "denali",     description: "Grizzly Bear Eating Berries"
NationalPark.create! image1: "denali09.jpg",    image2: "denali10.jpg",    name: "denali",     description: "Dall Sheep"
NationalPark.create! image1: "denali11.jpg",    image2: "denali12.jpg",    name: "denali",     description: "Caribou Grazing"
NationalPark.create! image1: "denali13.jpg",    image2: "denali14.jpg",    name: "denali",     description: "Dall Sheep Climbing"
NationalPark.create! image1: "denali15.jpg",    image2: "denali16.jpg",    name: "denali",     description: "Grizzly Bear Eating Berries"
NationalPark.create! image1: "denali17.jpg",    image2: "denali18.jpg",    name: "denali",     description: "Dall Sheep Climbing"
NationalPark.create! image1: "denali19.jpg",    image2: "denali20.jpg",    name: "denali",     description: "Changing Of The Colors For Fall"
NationalPark.create! image1: "denali21.jpg",    image2: "denali22.jpg",    name: "denali",     description: "Grizzly Bear Coming Up The Hill"
NationalPark.create! image1: "denali23.jpg",    image2: "denali24.jpg",    name: "denali",     description: "Dall Sheep On The Side Of The Road"
NationalPark.create! image1: "denali25.jpg",    image2: "denali26.jpg",    name: "denali",     description: "Grizzly Bear Running"
NationalPark.create! image1: "denali27.jpg",    image2: "denali28.jpg",    name: "denali",     description: "Grizzly Bear Looking For Berries"
NationalPark.create! image1: "denali29.jpg",    image2: "denali30.jpg",    name: "denali",     description: "Mount McKinley"
NationalPark.create! image1: "denali31.jpg",    image2: "denali32.jpg",    name: "denali",     description: "Dall Sheep Checking Me Out"    
NationalPark.create! image1: "everglades01.jpg",    image2: "everglades02.jpg",    name: "everglades",     description: "Welcome To The Swamp"
NationalPark.create! image1: "everglades03.jpg",    image2: "everglades04.jpg",    name: "everglades",     description: "Looking For Lunch"
NationalPark.create! image1: "everglades05.jpg",    image2: "everglades06.jpg",    name: "everglades",     description: "Summing On The Lawn"
NationalPark.create! image1: "everglades07.jpg",    image2: "everglades08.jpg",    name: "everglades",     description: "Baby Gatiors"
NationalPark.create! image1: "everglades09.jpg",    image2: "everglades10.jpg",    name: "everglades",     description: "Look At Me"
NationalPark.create! image1: "everglades11.jpg",    image2: "everglades12.jpg",    name: "everglades",     description: "Hiding"
NationalPark.create! image1: "everglades13.jpg",    image2: "everglades14.jpg",    name: "everglades",     description: "Turtle & Alligator Gar"
NationalPark.create! image1: "everglades15.jpg",    image2: "everglades16.jpg",    name: "everglades",     description: "Black & White"
NationalPark.create! image1: "everglades17.jpg",    image2: "everglades18.jpg",    name: "everglades",     description: "Nice An Swampy"
NationalPark.create! image1: "everglades19.jpg",    image2: "everglades20.jpg",    name: "everglades",     description: "Good Landing"
NationalPark.create! image1: "everglades21.jpg",    image2: "everglades22.jpg",    name: "everglades",     description: "Everglades NP"
NationalPark.create! image1: "everglades23.jpg",    image2: "everglades24.jpg",    name: "everglades",     description: "Our Ride In The Everglades"
NationalPark.create! image1: "everglades25.jpg",    image2: "everglades26.jpg",    name: "everglades",     description: "Do Not Disturb"
NationalPark.create! image1: "everglades27.jpg",    image2: "everglades28.jpg",    name: "everglades",     description: "A Deep Channel"
NationalPark.create! image1: "everglades29.jpg",    image2: "everglades30.jpg",    name: "everglades",     description: "Where That Gator"
NationalPark.create! image1: "everglades31.jpg",    image2: "everglades32.jpg",    name: "everglades",     description: "You Can't See Me"
NationalPark.create! image1: "everglades33.jpg",    image2: "everglades34.jpg",    name: "everglades",     description: "You Found Me"
NationalPark.create! image1: "everglades35.jpg",    image2: "everglades36.jpg",    name: "everglades",     description: "I Have A Kink In My Neck"
NationalPark.create! image1: "everglades37.jpg",    image2: "everglades38.jpg",    name: "everglades",     description: "Sunning On A Rock"
NationalPark.create! image1: "everglades39.jpg",    image2: "everglades40.jpg",    name: "everglades",     description: "Swamp Lily"
NationalPark.create! image1: "everglades41.jpg",    image2: "everglades42.jpg",    name: "everglades",     description: "I am Safe Here"
NationalPark.create! image1: "everglades43.jpg",    image2: "everglades44.jpg",    name: "everglades",     description: "Looking For Food"
NationalPark.create! image1: "everglades45.jpg",    image2: "everglades46.jpg",    name: "everglades",     description: "What You Looking At"
NationalPark.create! image1: "everglades47.jpg",    image2: "everglades48.jpg",    name: "everglades",     description: "That's Blood On My Lip"
NationalPark.create! image1: "grand_canyon01.jpg",  image2: "grand_canyon02.jpg",  name: "grand_canyon",   description: "Grand_Canyon NP"           
NationalPark.create! image1: "grand_canyon03.jpg",  image2: "grand_canyon04.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"         
NationalPark.create! image1: "grand_canyon05.jpg",  image2: "grand_canyon06.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"            
NationalPark.create! image1: "grand_canyon07.jpg",  image2: "grand_canyon08.jpg",  name: "grand_canyon",   description: "Grand Canyon NP" 
NationalPark.create! image1: "grand_canyon09.jpg",  image2: "grand_canyon10.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon11.jpg",  image2: "grand_canyon12.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon13.jpg",  image2: "grand_canyon14.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon15.jpg",  image2: "grand_canyon16.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon17.jpg",  image2: "grand_canyon18.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon19.jpg",  image2: "grand_canyon20.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon21.jpg",  image2: "grand_canyon22.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"
NationalPark.create! image1: "grand_canyon23.jpg",  image2: "grand_canyon24.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"
NationalPark.create! image1: "grand_canyon25.jpg",  image2: "grand_canyon26.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon27.jpg",  image2: "grand_canyon28.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon29.jpg",  image2: "grand_canyon30.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"     
NationalPark.create! image1: "grand_canyon31.jpg",  image2: "grand_canyon32.jpg",  name: "grand_canyon",   description: "Grand Canyon NP"
NationalPark.create! image1: "mesa_verde01.jpg",  image2: "mesa_verde02.jpg",  name: "mesa_verde",   description: "Cliff Palace"           
NationalPark.create! image1: "mesa_verde03.jpg",  image2: "mesa_verde04.jpg",  name: "mesa_verde",   description: "Cliff Palace"         
NationalPark.create! image1: "mesa_verde05.jpg",  image2: "mesa_verde06.jpg",  name: "mesa_verde",   description: "Cliff Palace"            
NationalPark.create! image1: "mesa_verde07.jpg",  image2: "mesa_verde08.jpg",  name: "mesa_verde",   description: "View Of The Cliffs" 
NationalPark.create! image1: "mesa_verde09.jpg",  image2: "mesa_verde10.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde11.jpg",  image2: "mesa_verde12.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde13.jpg",  image2: "mesa_verde14.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde15.jpg",  image2: "mesa_verde16.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde17.jpg",  image2: "mesa_verde18.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde19.jpg",  image2: "mesa_verde20.jpg",  name: "mesa_verde",   description: "Small Cliff Dwelling"     
NationalPark.create! image1: "mesa_verde21.jpg",  image2: "mesa_verde22.jpg",  name: "mesa_verde",   description: "Small Cliff Dwelling"     
NationalPark.create! image1: "mesa_verde23.jpg",  image2: "mesa_verde24.jpg",  name: "mesa_verde",   description: "Spruce Tree House"     
NationalPark.create! image1: "mesa_verde25.jpg",  image2: "mesa_verde26.jpg",  name: "mesa_verde",   description: "Spruce Tree House"     
NationalPark.create! image1: "mesa_verde27.jpg",  image2: "mesa_verde28.jpg",  name: "mesa_verde",   description: "Spruce Tree House"     
NationalPark.create! image1: "mesa_verde29.jpg",  image2: "mesa_verde30.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde31.jpg",  image2: "mesa_verde32.jpg",  name: "mesa_verde",   description: "Cliff Palace"
NationalPark.create! image1: "mesa_verde33.jpg",  image2: "mesa_verde34.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde35.jpg",  image2: "mesa_verde36.jpg",  name: "mesa_verde",   description: "Cliff Palace"
NationalPark.create! image1: "mesa_verde37.jpg",  image2: "mesa_verde38.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde39.jpg",  image2: "mesa_verde40.jpg",  name: "mesa_verde",   description: "Cliff Palace"
NationalPark.create! image1: "mesa_verde41.jpg",  image2: "mesa_verde42.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde43.jpg",  image2: "mesa_verde44.jpg",  name: "mesa_verde",   description: "Cliff Palace"
NationalPark.create! image1: "mesa_verde45.jpg",  image2: "mesa_verde46.jpg",  name: "mesa_verde",   description: "Cliff Palace"     
NationalPark.create! image1: "mesa_verde47.jpg",  image2: "mesa_verde48.jpg",  name: "mesa_verde",   description: "View From Entrance"
NationalPark.create! image1: "rocky_mtn_np01.jpg", image2: "rocky_mtn_np02.jpg", name: "rocky_mountain", description: "Moraine Park Elk"                
NationalPark.create! image1: "rocky_mtn_np03.jpg", image2: "rocky_mtn_np04.jpg", name: "rocky_mountain", description: "Water Flowing Over Downed Trees" 
NationalPark.create! image1: "rocky_mtn_np05.jpg", image2: "rocky_mtn_np06.jpg", name: "rocky_mountain", description: "Old Fall River Rd Mt Stream"     
NationalPark.create! image1: "rocky_mtn_np07.jpg", image2: "rocky_mtn_np08.jpg", name: "rocky_mountain", description: "Moraine Park Mt View"            
NationalPark.create! image1: "rocky_mtn_np09.jpg", image2: "rocky_mtn_np10.jpg", name: "rocky_mountain", description: "Bear Lake Fall Colors"           
NationalPark.create! image1: "rocky_mtn_np11.jpg", image2: "rocky_mtn_np12.jpg", name: "rocky_mountain", description: "Bear Lake Fall Colors"           
NationalPark.create! image1: "rocky_mtn_np13.jpg", image2: "rocky_mtn_np14.jpg", name: "rocky_mountain", description: "Bear Lake Fall Colors"           
NationalPark.create! image1: "rocky_mtn_np15.jpg", image2: "rocky_mtn_np16.jpg", name: "rocky_mountain", description: "Moraine Park Bridge"             
NationalPark.create! image1: "rocky_mtn_np17.jpg", image2: "rocky_mtn_np18.jpg", name: "rocky_mountain", description: "Aspen Leaves Flowing In Stream"             
NationalPark.create! image1: "rocky_mtn_np19.jpg", image2: "rocky_mtn_np20.jpg", name: "rocky_mountain", description: "Aspen Leaves Falling On The Ground"  
NationalPark.create! image1: "rocky_mtn_np21.jpg", image2: "rocky_mtn_np22.jpg", name: "rocky_mountain", description: "Trout Swimming In Stream"        
NationalPark.create! image1: "rocky_mtn_np23.jpg", image2: "rocky_mtn_np24.jpg", name: "rocky_mountain", description: "Moraine Park Mt View"            
NationalPark.create! image1: "rocky_mtn_np25.jpg", image2: "rocky_mtn_np26.jpg", name: "rocky_mountain", description: "Aspenglen Elk"                   
NationalPark.create! image1: "rocky_mtn_np27.jpg", image2: "rocky_mtn_np28.jpg", name: "rocky_mountain", description: "Old Fall River Rd Mt Stream"     
NationalPark.create! image1: "rocky_mtn_np29.jpg", image2: "rocky_mtn_np30.jpg", name: "rocky_mountain", description: "Pine Cones"                      
NationalPark.create! image1: "rocky_mtn_np31.jpg", image2: "rocky_mtn_np32.jpg", name: "rocky_mountain", description: "Pine Cones On The Ground"
NationalPark.create! image1: "valley_forge01.jpg",    image2: "valley_forge02.jpg",    name: "valley_forge",     description: "Visitor Center"
NationalPark.create! image1: "valley_forge03.jpg",    image2: "valley_forge04.jpg",    name: "valley_forge",     description: "Close Up Of Glass Pane"
NationalPark.create! image1: "valley_forge05.jpg",    image2: "valley_forge06.jpg",    name: "valley_forge",     description: "Valley Forge Memorial"
NationalPark.create! image1: "valley_forge07.jpg",    image2: "valley_forge08.jpg",    name: "valley_forge",     description: "The Generals"
NationalPark.create! image1: "valley_forge09.jpg",    image2: "valley_forge10.jpg",    name: "valley_forge",     description: "The Soldiers"
NationalPark.create! image1: "valley_forge11.jpg",    image2: "valley_forge12.jpg",    name: "valley_forge",     description: "Row Of Cannons"
NationalPark.create! image1: "valley_forge13.jpg",    image2: "valley_forge14.jpg",    name: "valley_forge",     description: "Single Cannon"
NationalPark.create! image1: "valley_forge15.jpg",    image2: "valley_forge16.jpg",    name: "valley_forge",     description: "Rows Of Cannons"
NationalPark.create! image1: "valley_forge17.jpg",    image2: "valley_forge18.jpg",    name: "valley_forge",     description: "More Cannons"
NationalPark.create! image1: "valley_forge19.jpg",    image2: "valley_forge20.jpg",    name: "valley_forge",     description: "Train Station"
NationalPark.create! image1: "valley_forge21.jpg",    image2: "valley_forge22.jpg",    name: "valley_forge",     description: "Geogre Washington's Headquarters"
NationalPark.create! image1: "valley_forge23.jpg",    image2: "valley_forge24.jpg",    name: "valley_forge",     description: "Geogre Washington's Bedroom"
NationalPark.create! image1: "valley_forge25.jpg",    image2: "valley_forge26.jpg",    name: "valley_forge",     description: "Officers Bedroom"
NationalPark.create! image1: "valley_forge27.jpg",    image2: "valley_forge28.jpg",    name: "valley_forge",     description: "Kitchen"
NationalPark.create! image1: "valley_forge29.jpg",    image2: "valley_forge30.jpg",    name: "valley_forge",     description: "A View From a Window"
NationalPark.create! image1: "valley_forge31.jpg",    image2: "valley_forge32.jpg",    name: "valley_forge",     description: "Continental Army Pennsylvania Division"
NationalPark.create! image1: "valley_forge33.jpg",    image2: "valley_forge34.jpg",    name: "valley_forge",     description: "Soldiers Huts"
NationalPark.create! image1: "valley_forge35.jpg",    image2: "valley_forge36.jpg",    name: "valley_forge",     description: "Soldiers Huts"
NationalPark.create! image1: "valley_forge37.jpg",    image2: "valley_forge38.jpg",    name: "valley_forge",     description: "Soldiers Huts"
NationalPark.create! image1: "valley_forge39.jpg",    image2: "valley_forge40.jpg",    name: "valley_forge",     description: "Soldiers Huts"
NationalPark.create! image1: "valley_forge41.jpg",    image2: "valley_forge42.jpg",    name: "valley_forge",     description: "Inside Soldiers Huts"
NationalPark.create! image1: "valley_forge43.jpg",    image2: "valley_forge44.jpg",    name: "valley_forge",     description: "Soldiers Huts"
NationalPark.create! image1: "valley_forge45.jpg",    image2: "valley_forge46.jpg",    name: "valley_forge",     description: "Soldiers Huts Foundations"
NationalPark.create! image1: "valley_forge47.jpg",    image2: "valley_forge48.jpg",    name: "valley_forge",     description: "Inside Soldiers Huts"
NationalPark.create! image1: "yellowstone01.jpg", image2: "yellowstone02.jpg", name: "yellowstone", description: "Geothermal Pool - Lake Yellowstone"                
NationalPark.create! image1: "yellowstone03.jpg", image2: "yellowstone04.jpg", name: "yellowstone", description: "Guyser About to Erupt" 
NationalPark.create! image1: "yellowstone05.jpg", image2: "yellowstone06.jpg", name: "yellowstone", description: "Firehole River"     
NationalPark.create! image1: "yellowstone07.jpg", image2: "yellowstone08.jpg", name: "yellowstone", description: "Geothermal Pot"            
NationalPark.create! image1: "yellowstone09.jpg", image2: "yellowstone10.jpg", name: "yellowstone", description: "Buffalo"           
NationalPark.create! image1: "yellowstone11.jpg", image2: "yellowstone12.jpg", name: "yellowstone", description: "Yellowstone River"           
NationalPark.create! image1: "yellowstone13.jpg", image2: "yellowstone14.jpg", name: "yellowstone", description: "River"           
NationalPark.create! image1: "yellowstone15.jpg", image2: "yellowstone16.jpg", name: "yellowstone", description: "Geothermal Pool"
NationalPark.create! image1: "yellowstone17.jpg", image2: "yellowstone18.jpg", name: "yellowstone", description: "Old Faithful" 
NationalPark.create! image1: "yellowstone19.jpg", image2: "yellowstone20.jpg", name: "yellowstone", description: "Grand Canyon Of the Yellowstone"     
NationalPark.create! image1: "yellowstone21.jpg", image2: "yellowstone22.jpg", name: "yellowstone", description: "Old Faithful"            
NationalPark.create! image1: "yellowstone23.jpg", image2: "yellowstone24.jpg", name: "yellowstone", description: "Yellowstone River"           
NationalPark.create! image1: "yellowstone25.jpg", image2: "yellowstone26.jpg", name: "yellowstone", description: "Geothermal Pools - Lake Yellowstone"           
NationalPark.create! image1: "yellowstone27.jpg", image2: "yellowstone28.jpg", name: "yellowstone", description: "Yellowstone River"           
NationalPark.create! image1: "yellowstone29.jpg", image2: "yellowstone30.jpg", name: "yellowstone", description: "Mule Deer" 
NationalPark.create! image1: "yellowstone31.jpg", image2: "yellowstone32.jpg", name: "yellowstone", description: "Lake Yellowstone" 
NationalPark.create! image1: "yellowstone33.jpg", image2: "yellowstone34.jpg", name: "yellowstone", description: "Buffaloes Grazing" 
NationalPark.create! image1: "yellowstone35.jpg", image2: "yellowstone36.jpg", name: "yellowstone", description: "Geothermal Pot" 
NationalPark.create! image1: "yellowstone37.jpg", image2: "yellowstone38.jpg", name: "yellowstone", description: "Geothermal Pot In Lake Yellowstone" 
NationalPark.create! image1: "yellowstone39.jpg", image2: "yellowstone40.jpg", name: "yellowstone", description: "Yellowstone River" 
NationalPark.create! image1: "yellowstone41.jpg", image2: "yellowstone42.jpg", name: "yellowstone", description: "Geothermal Pots"
NationalPark.create! image1: "yellowstone43.jpg", image2: "yellowstone44.jpg", name: "yellowstone", description: "Geothermal Green Pool"
NationalPark.create! image1: "yellowstone45.jpg", image2: "yellowstone46.jpg", name: "yellowstone", description: "Yellowstone River"
NationalPark.create! image1: "yellowstone47.jpg", image2: "yellowstone48.jpg", name: "yellowstone", description: "Yellowstone Falls"             
Occasion.create!    image1: "mowrer1ru01.jpg",    image2: "mowrer1ru02.jpg", category: "mowrer08172003", description: "Mowrer Reunion 2003 Bow, WA"    
Occasion.create!    image1: "mowrer1ru03.jpg",    image2: "mowrer1ru04.jpg", category: "mowrer08172003", description: "We Were All There"              
Occasion.create!    image1: "mowrer1ru05.jpg",    image2: "mowrer1ru06.jpg", category: "mowrer08172003", description: "New Mexico Descendants"         
Occasion.create!    image1: "mowrer1ru07.jpg",    image2: "mowrer1ru08.jpg", category: "mowrer08172003", description: "Missouri Descendants"           
Occasion.create! image1: "karrie_wedding01.jpg", image2: "karrie_wedding02.jpg", category: "karrie10272007", sub_category: "wedding",    description: "Wedding Party"                   
Occasion.create! image1: "karrie_wedding03.jpg", image2: "karrie_wedding04.jpg", category: "karrie10272007", sub_category: "dance",      description: "Karrie & Dad Dancing"            
Occasion.create! image1: "karrie_wedding05.jpg", image2: "karrie_wedding06.jpg", category: "karrie10272007", sub_category: "wedding",    description: "Karrie, Mom & Dad"               
Occasion.create! image1: "karrie_wedding07.jpg", image2: "karrie_wedding08.jpg", category: "karrie10272007", sub_category: "rehearsal",  description: "Mom, Dad, Karrie, Bob & Jessica" 
Occasion.create! image1: "karrie_wedding09.jpg", image2: "karrie_wedding10.jpg", category: "karrie10272007", sub_category: "before",     description: "Karrie & Milana Getting Ready"   
Occasion.create! image1: "karrie_wedding11.jpg", image2: "karrie_wedding12.jpg", category: "karrie10272007", sub_category: "wedding",    description: "Milana The Flower Girl"          
Occasion.create! image1: "karrie_wedding13.jpg", image2: "karrie_wedding14.jpg", category: "karrie10272007", sub_category: "wedding",    description: "Dad Giving The Bride Away"       
Occasion.create! image1: "karrie_wedding15.jpg", image2: "karrie_wedding16.jpg", category: "karrie10272007", sub_category: "rehearsal",  description: "Dava, Bill & Russel"             
Occasion.create! image1: "karrie_wedding17.jpg", image2: "karrie_wedding18.jpg", category: "karrie10272007", sub_category: "before",     description: "Karrie Getting Hair Styled"      
Occasion.create! image1: "karrie_wedding19.jpg", image2: "karrie_wedding20.jpg", category: "karrie10272007", sub_category: "wedding",    description: "Milana What Going On???"         
Occasion.create! image1: "karrie_wedding21.jpg", image2: "karrie_wedding22.jpg", category: "karrie10272007", sub_category: "rehearsal",  description: "Sisters Jessica & Karrie"        
Occasion.create! image1: "karrie_wedding23.jpg", image2: "karrie_wedding24.jpg", category: "karrie10272007", sub_category: "wedding",    description: "The First Kiss"                  
Occasion.create! image1: "karrie_wedding25.jpg", image2: "karrie_wedding26.jpg", category: "karrie10272007", sub_category: "wedding",    description: "Milana & Grandpa Dancing"        
Occasion.create! image1: "karrie_wedding27.jpg", image2: "karrie_wedding28.jpg", category: "karrie10272007", sub_category: "wedding",    description: "I am The Boss"                    
Occasion.create! image1: "karrie_wedding29.jpg", image2: "karrie_wedding30.jpg", category: "karrie10272007", sub_category: "wedding",    description: "The Bride & Groom Smiling"       
Occasion.create! image1: "karrie_wedding31.jpg", image2: "karrie_wedding32.jpg", category: "karrie10272007", sub_category: "wedding",    description: "The Two Families"                
Title.create! name: "arches",           description: "ARCHES NATIONAL PARK: is a U.S. National Park in eastern Utah. The park is located on the Colorado River north of Moab, Utah. It is known for preserving over 2000 natural sandstone arches, including the world famous Delicate Arch, in addition to a variety of unique geological resources and formations.  The park is located just outside of Moab, Utah, and is 76,359 acres in area. Its highest elevation is 5,653 feet at Elephant Butte, and its lowest elevation is 4,085 feet at the visitor center. Forty three arches have collapsed due to erosion since 1970. The park receives 10 inches of rain a year on average.  Administered by the National Park Service, the area was originally created as a National Monument on April 12, 1929. It was designated as a National Park on November 12, 1971." 
Title.create! name: "bent_fort",        description: "BENT'S OLD FORT NATIONAL HISTORICAL SITE: (also referred to as Fort William) is an 1833 fort located in Otero County in southeastern Colorado, 6 east miles from La Junta.  William and Charles Bent, along with Ceran St. Vrain, built the fort to trade with Southern Cheyenne and Arapaho Plains Indians and trappers for buffalo robes.  Bent's Fort is described as having been a structure built of adobe bricks. It was 180 feet long and 135 feet wide. The walls were 15 feet in height and four feet thick and it was the strongest post at that time west of Ft. Leavenworth. The walls of the fort served as walls of the rooms, all of which faced inwardly on a court or plaza.  Entrance was through large wooden gates of very heavy timbers.  For much of its 16-year history, the fort was the only major permanent settlement on the Santa Fe Trail between Missouri and the Mexican settlements.  It was destroyed under mysterious circumstances in 1849.  The area of the fort was designated a National Historic Site on June 3, 1960.  The fort was reconstructed and is open to the public, this was recreation day with people playing different roles"
Title.create! name: "black_canyon",     description: "BLACK CANYON OF THE GUNNISION NATIONAL PARK:  located in western CO.  There are three entrances to the park. The more-developed east entrance is located 37 miles east of Montrose and just west of Blue Mesa Reservoir by Blue Mesa Point.  The park contains 12 miles of the 48-mile long canyon of the Gunnison River.  It became a National Park on October 21, 1999. The park itself contains the deepest and most dramatic section of the canyon.  The Gunnison River drops an average of 34 feet per mile through the entire canyon, making it the 5th steepest mountain descent in North America.  The Black Canyon is so named due its steepness which makes it difficult for sunlight to penetrate into its depths. As a result, the canyon is often shrouded in shadow, causing the rocky walls to appear black. At its narrowest point the canyon is only 40 feet wide at the river.  The extreme steepness and depth of the Black Canyon formed as the result of several geologic processes acting together."
Title.create! name: "bryce_canyon",     description: "BRYCE CANYON NATIONAL PARK: located in southwestern Utah, about 92 miles East of Cedar City, Utah. The major feature of the park is Bryce Canyon, which despite its name, is not a canyon but a collection of giant natural amphitheaters along the eastern side of the Paunsaugunt Plateau. Bryce is distinctive due to geological structures called hoodoos, formed by frost weathering and stream erosion of the river and lake bed sedimentary rocks. The red, orange, and white colors of the rocks provide spectacular views for park visitors. The rim at Bryce varies from 8,000 to 9,000 feet."  
Title.create! name: "denali",           description: "DENALI NATIONAL PARK:  the entrance is located 11 miles south of Healy, in Interior Alaska, centered on Denali (Mount McKinley), 20,237 feet, the highest mountain in North America. The park encompasses more than 6 million acres.  The park was established as Mount McKinley National Park on February 26, 1917.  Denali's landscape is a mix of forest at the lowest elevations, including deciduous taiga. The preserve is also home to tundra at middle elevations, and glaciers, rock, and snow at the highest elevations.  Denali is home to a variety of birds and mammals, including grizzly bears, black bears, caribou, dall sheep, moose, grey wolves and many smaller animals and birds including golden eagle The park is serviced by a 91-mile road, only a small fraction of the road is paved. The first 15 miles of the road are available to private vehicles. Beyond this point, visitors must access the interior of the park through concessionary buses. Wonder Lake can be reached by a six-hour bus ride from the Wilderness Access Center.  Today, 400,000 people visit the park annually."
Title.create! name: "everglades",       description: "EVERGLADES NATIONAL PARK:  located in South Florida and spans 3 counties, covering 1.5 million acres. There are 3 ways to access the park by car. The main entrance located in Homestead, the Shark Valley in Miami and the Gulf Coast Everglades City.  It is the largest tropical wilderness, the largest wilderness of any kind east of the Mississippi River, and is visited on average by one million people each year.  The Everglades are a network of wetlands and forests fed by a river flowing .25 miles per day out of Lake Okeechobee, southwest into Florida Bay.  The Park is the most significant breeding ground for tropical wading birds in North America, contains the largest mangrove ecosystem in the western hemisphere, is home to 36 threatened or protected species including the Florida panther, the American crocodile, and the West Indian manatee, and supports 350 species of birds, 300 species of fresh and saltwater fish, 40 species of mammals, and 50 species of reptiles."
Title.create! name: "grand_canyon",     description: "GRAND CANYON NATIONAL PARK:  located in Northern Arizona.  The South Rim is 80 mile northwest of Flagstaff or 60 miles north of Williams.  The park's central feature is the Grand Canyon, a gorge of the Colorado River, which is often considered one of the Seven Natural Wonders of the World. The park covers 1,217,262 acres (1,902 sq. miles) of unincorporated areas in Coconino and Mohave counties.  In 1919, it became an official national park.  The Grand Canyon, including its extensive system of tributary canyons, is valued for its combination of size, depth, and exposed layers of colorful rocks dating back to Precambrian times. The canyon itself was created by the incision of the Colorado River and its tributaries after the Colorado Plateau was uplifted, causing the Colorado River system to develop along its present path."
Title.create! name: "grand_teton",      description: "GRAND TETON NATIONAL PARK: is located in northwestern Wyoming, just outside Jackson Hole, WY. At approximately 310,000 acres, the park includes the major peaks of the 40-mile-long Teton Range as well as most of the northern sections of the valley known as Jackson Hole.  It averages of 2.5 million visitors annually.  The park is named for Grand Teton, the tallest mountain in the Teton Range.At 13,775 feet, Grand Teton abruptly rises more than 7,000 feet above Jackson Hole.  The park has numerous lakes, including 15-mile-long Jackson Lake as well as streams of varying length and the upper main stem of the Snake River. A dozen small glaciers persist at the higher elevations near the highest peaks in the range. Grand Teton National Park is an almost pristine ecosystem and the same species of flora and fauna that have existed since prehistoric times can still be found there. More than 1,000 species of vascular plants, dozens of species of mammals, 300 species of birds, more than a dozen fish species and a few species of reptiles and amphibians exist."
Title.create! name: "hawaii_volcanoes", description: "HAWAII VOLCANOES NATIONAL PARK: is located on the island of Hawaii, HI, 30 miles southwest of Hilo.  The park includes 323,431 acres and encompasses two active volcanoes: Maunaloa which lasted erupted in 1984 it is the world's most massive sub aerial volcano and Kilauea, which has been erupting since Jan 3rd, 1983 is one of the world's most active volcanoes.  This prolific volcano currently produces 250,000 to 650,000 cubic yards of lava a day.  The park gives scientists insight into the birth of the Hawaiian Islands and ongoing studies into the processes of volcanism. For visitors, the park offers dramatic volcanic landscapes as well as glimpses of rare flora and fauna.  Established as Hawaii National Park in 1916.  Kilauea and its Halema'uma'u caldera were traditionally considered the sacred home of the volcano goddess Pele, and Hawaiians visited the crater to offer gifts to the goddess."
Title.create! name: "independance",     description: "INDEPENDENCE NATIONAL HISTORICAL PARK: is located in Philadelphia, PA.  It preserves several sites associated with the American Revolution and the nation's founding history.  The 55-acre park comprises much of the 'Old City' historic district. The park has been nicknamed 'America's most historic square mile' because of its abundance of historic landmarks.  The centerpiece of the park is Independence Hall, where the Declaration of Independence and the United States Constitution were debated and adopted in the late 18th century. Independence Hall was the principal meetinghouse of the Second Continental Congress from 1775 to 1783 and the Constitutional Convention in the summer of 1787. Across the street from Independence Hall, the Liberty Bell, an iconic symbol of American independence, is displayed in the Liberty Bell Center. Most of the park's historic structures are located in the vicinity of the four landscaped blocks between Chestnut, Walnut, 2nd, and 6th streets."
Title.create! name: "mesa_verde",       description: "MESA VERDE NATIONAL PARK:  is located in southwest, CO near the Four Corners. It is the largest archaeological preserve in the United States.  The park covers 52,000 acres and elevations ranging from about 6,000 to 8,572 feet.  The park was created in 1906 by President Theodore Roosevelt to protect some of the best-preserved cliff dwellings in the world. It is the only cultural National Park set aside by the National Park System.  It occupies 81.4 square miles and features numerous ruins of homes and villages built by the Ancient Pueblo peoples, sometimes called the Anasazi. There are over 4000 archaeological sites and over 600 cliff dwellings of the Pueblo people at the site.  Mesa Verde is best known for cliff dwellings, which are structures built within caves and under outcroppings in cliffs, including Cliff Palace, thought to be the largest cliff dwelling in North America.  The Anasazi inhabited Mesa Verde between 600 to 1300 or the start of the 15th century."
Title.create! name: "rocky_mountain",   description: "ROCKY MOUNTAIN NATIONAL PARK: is a national park located in the north-central region of Colorado.  The main entrance is just outside the town of Estes Park. It features majestic mountain views, mountain lakes, a variety of wildlife, varied climates and environments from wooded forests to mountain tundra and easy access to back country trails and campsites. The park is located northwest of Boulder, Colorado, in the Rockies, and includes the Continental Divide and the headwaters of the Colorado River.  The park has five visitor centers. The park headquarters, Beaver Meadows Visitor Center, is a National Historic Landmark, designed by the Frank Lloyd Wright School of Architecture at Taliesin West.  Trail Ridge Road runs through the park, runs from the town of Estes Park on the east to Grand Lake on the southwest. The road reaches an elevation of 12,183 feet, and is closed by snow in winter."
Title.create! name: "valley_forge",     description: "VALLEY FORGE NATIONAL HISTORICAL PARK: is the site of the third winter encampment of the Continental Army during the American Revolutionary War, taking place from December 19, 1777 to June 19, 1778. The National Historical Park preserves the site and interprets the history of the Valley Forge encampment.  The Park contains historical buildings, recreated encampment structures, memorials, museums, and recreation facilities.  Originally Valley Forge State Park, in 1976, Pennsylvania gave the park as a gift to the nation for the Bicentennial. The U.S. Congress passed a law, signed by President Gerald Ford on July 4, 1976, authorizing the addition of Valley Forge National Historical Park.  It is located in Valley Forge, PA.  The park encompasses 3,500 acres and is visited by over 1.2 million people each year. Visitors can see restored historic structures, reconstructed structures such as the iconic log huts, and monuments erected by the states from which the Continental soldiers came." 
Title.create! name: "yellowstone",      description: "YELLOWSTONE NATIONAL PARK: is located primarily in WY, although it also extends into MT and ID. There are five entrances. It was established on March 1, 1872.  Its widely held to be the first national park in the world, is known for its wildlife and its many geothermal features, especially Old Faithful Geyser, one of the most popular features in the park.  Grizzly bears, wolves, and free-ranging herds of bison and elk live in the park. It has many types of ecosystems, but the subalpine forest is most abundant. It is part of the South Central Rockies forests ecoregion.  The park spans an area of 3,468 square miles comprising lakes, canyons, rivers and mountain ranges.  Yellowstone Lake is centered over the Yellowstone Caldera, the largest super volcano on the continent. The caldera is considered an active volcano. It has erupted with tremendous force several times in the last two million years.  Half of the world's geothermal features are in Yellowstone, fueled by this ongoing volcanism.  Lava flows and rocks from volcanic eruptions cover most of the land area of Yellowstone. The park is the centerpiece of the Greater Yellowstone Ecosystem, the largest remaining nearly-intact ecosystem in the Earth's northern temperate zone."
Title.create! name: "zion",             description: "ZION NATIONAL PARK: is located near Springdale, Utah. A prominent feature of the 229 square mile park is Zion Canyon, which is 15 miles long and up to half a mile deep, cut through the reddish and tan-colored Navajo Sandstone by the North Fork of the Virgin River. Ranging in elevation from 3,666 feet to 8,726 feet.  Numerous plant species as well as 289 species of birds, 75 mammals and 32 reptiles inhabit the park's four life zones: desert, riparian, woodland, and coniferous forest. Zion National Park includes mountains, canyons, buttes, mesas, monoliths, rivers, slot canyons, and natural arches.  In 1909, U.S. President William Howard Taft named the area a National Monument to protect the canyon, under the name of Mukuntuweap National Monument. In 1918, however, the acting director of the newly created National Park Service changed the park's name to Zion.  The new name, Zion, had greater appeal to an ethnocentric audience.  It was established as a National Park on November 19, 1919."
Title.create! name: "karrie10272007",   description: "Karrie Mowrer and Bob Kirik were married on October 27th 2007 in Longmont, Colorado at Saint John the Baptist Catholic Church.  The reception was held at Fox Hill Country Club.  Many of Bob's family made the trip from Pennsylvania to Longmont, Colorado."
Title.create! name: "mowrer08172003",   description: "The MOWRER REUNION: was hosted by Jim and Bev Mowrer in Bow, Washington on July 17, 2003.  Guest came from Alaska, California, Colorado, Connecticut, Missouri, Washington and as far away as Germany.  For many this was the first time we had met.  We were able to trace our roots back to our Grandfathers, Great Grandfathers and for others Great, Great Grandfathers from Missouri.  I knew my grandfather, lived in Washington in the late 1800's, moved from Missouri with his brother.  He later moved and homesteaded in Ramah, New Mexico, as it was too wet in Washington. We had reunions with my Grandfathers descendants in Durango, Colorado, for several years until cousin Jimmy's cabin burnt down."