Location.create! name: "Alaska"
Location.create! name: "Albuquerque Balloons"
Location.create! name: "Arches NP"
Location.create! name: "Bent Fort National Historical Site"
Location.create! name: "Black Canyon NP"
Location.create! name: "Bryce Canyon NP"
Location.create! name: "Colorado"
Location.create! name: "Denali NP"
Location.create! name: "Everglades NP"
Location.create! name: "Fall Colors"
Location.create! name: "Florida"
Location.create! name: "Grand Canyon NP"
Location.create! name: "Hawaii"
Location.create! name: "Hawaii Volcanoes NP"
Location.create! name: "Independence National Historical Park"
Location.create! name: "Jacksonville Air Show"
Location.create! name: "Kenai Fjords NP"
Location.create! name: "Mesa Verde NP"
Location.create! name: "Rocky Mountain NP"
Location.create! name: "Special Occasions"
Location.create! name: "Valley Forge NP"
Location.create! name: "Yellowstone NP"