Picture.create! image1: "sedona01.jpg",       image2: "sedona02.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"                
Picture.create! image1: "sedona03.jpg",       image2: "sedona04.jpg",       category: "sedona",       description: "Red Rocks Of Sedona" 
Picture.create! image1: "sedona05.jpg",       image2: "sedona06.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"     
Picture.create! image1: "sedona07.jpg",       image2: "sedona08.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"            
Picture.create! image1: "sedona09.jpg",       image2: "sedona10.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"           
Picture.create! image1: "sedona11.jpg",       image2: "sedona12.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"           
Picture.create! image1: "sedona13.jpg",       image2: "sedona14.jpg",       category: "sedona",       description: "A View of Sedona"           
Picture.create! image1: "sedona15.jpg",       image2: "sedona16.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"             
Picture.create! image1: "sedona17.jpg",       image2: "sedona18.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"             
Picture.create! image1: "sedona19.jpg",       image2: "sedona20.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"  
Picture.create! image1: "sedona21.jpg",       image2: "sedona22.jpg",       category: "sedona",       description: "Chapel Ot The Holy Cross"        
Picture.create! image1: "sedona23.jpg",       image2: "sedona24.jpg",       category: "sedona",       description: "That's A Big House"            
Picture.create! image1: "sedona25.jpg",       image2: "sedona26.jpg",       category: "sedona",       description: "A View of Sedona"                   
Picture.create! image1: "sedona27.jpg",       image2: "sedona28.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"     
Picture.create! image1: "sedona29.jpg",       image2: "sedona30.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"                      
Picture.create! image1: "sedona31.jpg",       image2: "sedona32.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"
Picture.create! image1: "sedona33.jpg",       image2: "sedona34.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"            
Picture.create! image1: "sedona35.jpg",       image2: "sedona36.jpg",       category: "sedona",       description: "Snow On The Red Rocks"                   
Picture.create! image1: "sedona37.jpg",       image2: "sedona38.jpg",       category: "sedona",       description: "A View of Sedona"     
Picture.create! image1: "sedona39.jpg",       image2: "sedona40.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"                      
Picture.create! image1: "sedona41.jpg",       image2: "sedona42.jpg",       category: "sedona",       description: "Red Rocks Of Sedona"
Picture.create! image1: "sedona43.jpg",       image2: "sedona44.jpg",       category: "sedona",       description: "Snow On The Red Rocks"
Picture.create! image1: "sedona45.jpg",       image2: "sedona46.jpg",       category: "sedona",       description: "Red Rock Of Sedona"
Picture.create! image1: "sedona47.jpg",       image2: "sedona48.jpg",       category: "sedona",       description: "Red Rock Of Sedona"
